### ISSUE TITLE
Remove duplicate recurring events

### ISSUE THREAD

**Issue by marksie1988** [marksie1988/atomic_calendar#514]
## Expected behaviour

When there are repetitive events e.g. daily / weekly there should be an option to only show x many of these e.g. over the next 7days or 30days

## Current behaviour

Cant currently do this only able to hideDuplicates of the same event on the same day. 

## Possible solutions

Add a new option `recurringEvent: 7` which would remove any events with the same title at the same time after 7 days. 

## Context and reason

User requested as the calendar is flooded with these events such as football practice which aren't needed to be shown until the week they happen. 

## Checklist

- [x] I searched the current issues and the feature is not known.
- [x] I am mostly sure that the feature will bring more good than bad.

**Comment by bozzobrain** [comment]
Recurring events, such as birthdays, appear on every month on the day they occur on. I believe this is covered under this issue? Is there a workaround or solution for this type of issue?

**Comment by bkr1969** [comment]
Please respond if this repository is still being maintained.  It does not appear to be.
